apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g73i5s5lk-java-quarkus
  janus-idp.io/tekton: g73i5s5lk-java-quarkus
  backstage.io/kubernetes-id: g73i5s5lk-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g73i5s5lk-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
